version: '3.8'

services:
  # Existing services from your main docker-compose.yaml
  nginx:
    image: nginx:alpine
    container_name: suna-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - suna-network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: suna-certbot
    restart: "no"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email your-email@example.com --agree-tos --no-eff-email
      --staging -d app.autobro.cloud
    depends_on:
      - nginx

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  suna-network:
    external: true



